name: folk
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.4.0+14

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_facebook_login: 2.0.0
  firebase_auth: ^0.15.4

  cupertino_icons: ^0.1.2
  http: ^0.12.0+4
  flutter_datetime_picker: ^1.4.0
  flutter_country_picker: ^0.1.6
  cached_network_image: ^2.0.0
  flutter_screenutil: ^1.1.0
  socket_io_client: ^0.9.9
  fluttertoast: ^3.1.0
  bubble: ^1.1.9+1
  gallery_saver: ^1.0.7
  permission_handler: 4.2.0
  pull_to_refresh: ^1.5.8
  fimber: ^0.4.0
  timeago: ^2.0.26
  google_fonts: ^0.3.5
  provider: ^4.0.2
  shared_preferences: ^0.5.6+1
  image_picker:
  firebase_messaging: ^6.0.13
  flutter_local_notifications: ^1.2.1
  share: ^0.6.3+6
  font_awesome_flutter: ^8.7.0
  overlay_support: ^1.0.3
  device_info: ^0.4.2+1
  uuid: ^2.0.4
  photo_view: ^0.9.1
  line_awesome_icons: ^1.0.4+2
  line_icons: ^0.2.0
  intl: 0.16.1
  flutter_sound: ^2.1.1
  file: ^5.0.4
  # modal_bottom_sheet: ^0.1.5
  image_cropper:
  admob_flutter: "^1.0.0-beta.2"
  simple_animations: ^1.3.3
  progress_dialog: ^1.2.0
  awesome_dialog: ^0.1.0
  flutter_alert: ^0.4.0
  carousel_slider: ^1.4.1
  flutter_map: ^0.9.0
  percent_indicator: ^2.1.1+1
  custom_switch: ^0.0.1
  geolocator: ^5.3.1
  slide_countdown_clock: ^1.0.3
  flutter_skeleton: ^0.1.0+1
  google_maps_place_picker: ^0.9.5
  simple_auth: ^2.0.5
  simple_auth_flutter: ^2.0.7
  dio: ^3.0.9

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"

dev_dependencies:
  flutter_launcher_icons: "^0.7.3"
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
    - lang/en.json
    - lang/it.json

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
